/**
 * The console's offline event queue (`FR-OFF-01`, FRONTEND.md §11.1).
 *
 * A reception counter keeps working when the network does not. Every queue
 * action is written here first, applied to local state immediately, and pushed
 * to the server when there is a server to push to. Nothing is lost by being
 * offline; the only difference a receptionist should notice is a number in the
 * corner telling her how much is waiting to go.
 *
 * ## Why the store is an interface
 *
 * The real store is IndexedDB via Dexie (FRONTEND.md §9), which exists in a
 * browser and not in a test runner. Putting the persistence behind a two-method
 * interface means the queue's actual logic — ordering, retry, the pending
 * count, what happens to a conflicted entry — is testable in plain Node,
 * without a headless browser standing in for a decision that has nothing to do
 * with storage.
 *
 * `createDexieStore` in `./store.dexie.ts` is the browser implementation;
 * `createMemoryStore` below is the one the tests use, and is also what a
 * server-rendered first paint gets before IndexedDB opens.
 */

import type { QueueEventType } from '@platform/domain';

/** An action taken locally, waiting to reach the server. */
export interface PendingEvent {
  /** The idempotency key. Generated once, at the moment of the tap (`SY-02`). */
  readonly clientEventId: string;
  readonly sessionId: string;
  readonly type: QueueEventType;
  readonly payload: Record<string, unknown>;
  /** The console's clock. Orders the batch within itself only (`SY-01`). */
  readonly clientTs: string;
  /** How many times a push has been attempted and failed. */
  readonly attempts: number;
  /** Set when the server refused it, so the UI can explain and roll back. */
  readonly conflict?: { readonly reason: string; readonly code: string };
}

/** What the queue needs from storage, and nothing more. */
export interface PendingStore {
  all(): Promise<PendingEvent[]>;
  put(event: PendingEvent): Promise<void>;
  remove(clientEventIds: readonly string[]): Promise<void>;
  clear(): Promise<void>;
}

/** In-memory store, for tests and for the moment before IndexedDB opens. */
export function createMemoryStore(): PendingStore {
  const rows = new Map<string, PendingEvent>();

  return {
    // eslint-disable-next-line @typescript-eslint/require-await -- satisfies the async interface
    async all() {
      return [...rows.values()].sort(byClientTimestamp);
    },
    // eslint-disable-next-line @typescript-eslint/require-await -- satisfies the async interface
    async put(event) {
      rows.set(event.clientEventId, event);
    },
    // eslint-disable-next-line @typescript-eslint/require-await -- satisfies the async interface
    async remove(clientEventIds) {
      for (const id of clientEventIds) rows.delete(id);
    },
    // eslint-disable-next-line @typescript-eslint/require-await -- satisfies the async interface
    async clear() {
      rows.clear();
    },
  };
}

/**
 * The result of one push attempt, as the console needs to act on it.
 */
export interface FlushOutcome {
  /** Entries the server took. Removed from the queue. */
  readonly accepted: readonly string[];
  /** Entries the server refused. Removed, and the row rolls back (`SY-03`). */
  readonly conflicted: readonly { readonly clientEventId: string; readonly reason: string }[];
  /** True when the push never reached the server; everything stays queued. */
  readonly offline: boolean;
}

/** What `flush` needs to talk to the server. Injected, so it can be faked. */
export type PushTransport = (
  sessionId: string,
  events: readonly PendingEvent[],
) => Promise<{
  readonly accepted: readonly { readonly clientEventId: string }[];
  readonly conflicts: readonly {
    readonly clientEventId: string;
    readonly reason: string;
    readonly code: string;
  }[];
}>;

/**
 * How many attempts before an entry is considered stuck.
 *
 * Not discarded — never discarded. A stuck entry is surfaced to the operator,
 * because an action a receptionist took and the system silently dropped is the
 * worst outcome this design can produce.
 */
export const MAX_ATTEMPTS = 8;

export class OfflineQueue {
  constructor(private readonly store: PendingStore) {}

  /** Everything still waiting, oldest first. */
  async pending(): Promise<PendingEvent[]> {
    return await this.store.all();
  }

  /** The number the console shows in its offline block (`FR-OFF-01`). */
  async pendingCount(): Promise<number> {
    return (await this.store.all()).length;
  }

  /**
   * Records an action taken locally.
   *
   * The key is generated by the caller at the moment of the tap rather than
   * here, because the same key has to travel with the optimistic update so a
   * later conflict can be matched back to the row it belongs to.
   */
  async enqueue(event: Omit<PendingEvent, 'attempts'>): Promise<void> {
    await this.store.put({ ...event, attempts: 0 });
  }

  /**
   * Pushes everything queued for one session.
   *
   * Entries the server accepted or refused are both removed: an accepted one
   * is in the log, and a refused one will never be accepted however many times
   * it is sent (`SY-03` — it lost a race that is already over). Only a network
   * failure leaves the queue intact, which is what makes a dropped connection
   * cost nothing.
   */
  async flush(sessionId: string, push: PushTransport): Promise<FlushOutcome> {
    const queued = (await this.store.all()).filter((event) => event.sessionId === sessionId);
    if (queued.length === 0) {
      return { accepted: [], conflicted: [], offline: false };
    }

    try {
      const result = await push(sessionId, queued);

      const accepted = result.accepted.map((entry) => entry.clientEventId);
      const conflicted = result.conflicts.map((entry) => ({
        clientEventId: entry.clientEventId,
        reason: entry.reason,
      }));

      await this.store.remove([...accepted, ...conflicted.map((entry) => entry.clientEventId)]);
      return { accepted, conflicted, offline: false };
    } catch {
      // The push never landed. Everything stays queued and the attempt count
      // rises, which is what drives the backoff and the stuck warning.
      for (const event of queued) {
        await this.store.put({ ...event, attempts: event.attempts + 1 });
      }
      return { accepted: [], conflicted: [], offline: true };
    }
  }

  /** Entries that have failed enough times to be worth telling someone about. */
  async stuck(): Promise<PendingEvent[]> {
    return (await this.store.all()).filter((event) => event.attempts >= MAX_ATTEMPTS);
  }

  /** Used after a forced re-pull (`SY-06`), where the local log is discarded. */
  async clear(): Promise<void> {
    await this.store.clear();
  }
}

/**
 * Retry delay for attempt `n`, in milliseconds.
 *
 * Exponential from one second, capped at thirty. The cap matters more than the
 * curve: a console that has been offline for an hour must retry often enough
 * to notice the network within half a minute of it returning, or a receptionist
 * stands there wondering why the pending count is not moving.
 *
 * Deterministic rather than jittered. There is one console per counter, not a
 * thundering herd, and a predictable delay is one an operator can be told
 * about ("it will try again in a few seconds").
 */
export function retryDelayMs(attempts: number): number {
  return Math.min(30_000, 1_000 * 2 ** Math.max(0, attempts));
}

function byClientTimestamp(a: PendingEvent, b: PendingEvent): number {
  if (a.clientTs === b.clientTs) return a.clientEventId < b.clientEventId ? -1 : 1;
  return a.clientTs < b.clientTs ? -1 : 1;
}
